# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesteddepartment',
            name='department_contact_position',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
