# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-10 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotations', '0003_rotation_request_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rotationrequestforwardresponse',
            name='forward',
        ),
        migrations.RemoveField(
            model_name='rotationrequestforward',
            name='key',
        ),
        migrations.DeleteModel(
            name='RotationRequestForwardResponse',
        ),
    ]
