# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-30 18:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rotations', '0004_auto_20161210_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotationrequestforward',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 12, 30, 18, 55, 38, 213273, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rotationrequestforward',
            name='memo_file',
            field=models.FileField(default='', upload_to='forward_memos'),
            preserve_default=False,
        ),
    ]
