# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-30 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_auto_20170130_0703'),
        ('rotations', '0005_auto_20161230_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotation',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='hospitals.Hospital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rotation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='hospitals.Location'),
        ),
        migrations.AddField(
            model_name='rotationrequest',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rotation_requests', to='hospitals.Hospital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rotationrequest',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rotation_requests', to='hospitals.Location'),
        ),
    ]
