# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-29 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotations', '0005_auto_20161230_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotationrequest',
            name='request_memo',
            field=models.FileField(blank=True, null=True, upload_to='request_memos'),
        ),
    ]
