# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-30 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotations', '0006_auto_20170130_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesteddepartment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='requesteddepartment',
            name='department_hospital',
        ),
        migrations.RemoveField(
            model_name='requesteddepartment',
            name='department_specialty',
        ),
        migrations.RemoveField(
            model_name='rotation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='rotationrequest',
            name='requested_department',
        ),
        migrations.DeleteModel(
            name='RequestedDepartment',
        ),
    ]
