# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 21:37
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=9)),
                ('badge_number', models.CharField(max_length=9)),
                ('phone_number', models.CharField(max_length=16)),
                ('mobile_number', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=128)),
                ('saudi_id_number', models.CharField(max_length=10)),
                ('passport_number', models.CharField(max_length=10)),
                ('medical_record_number', models.CharField(max_length=10)),
                ('contact_person_name', models.CharField(max_length=64)),
                ('contact_person_relation', models.CharField(max_length=32)),
                ('contact_person_mobile', models.CharField(max_length=16)),
                ('contact_person_email', models.EmailField(max_length=64)),
                ('gpa', models.FloatField(validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('staff', 'Staff member'), ('intern', 'Intern')], max_length=8)),
                ('ar_first_name', models.CharField(max_length=32)),
                ('ar_middle_name', models.CharField(max_length=32)),
                ('ar_last_name', models.CharField(max_length=32)),
                ('en_first_name', models.CharField(max_length=32)),
                ('en_middle_name', models.CharField(max_length=32)),
                ('en_last_name', models.CharField(max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='intern',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intern', to='accounts.Profile'),
        ),
    ]
