# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 11:20
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import userena.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=9)),
                ('badge_number', models.CharField(max_length=9)),
                ('phone_number', models.CharField(max_length=16)),
                ('mobile_number', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=128)),
                ('saudi_id_number', models.CharField(max_length=10)),
                ('saudi_id', models.ImageField(upload_to='saudi_ids')),
                ('passport_number', models.CharField(max_length=10)),
                ('passport', models.ImageField(upload_to='passports')),
                ('medical_record_number', models.CharField(max_length=10)),
                ('contact_person_name', models.CharField(max_length=64)),
                ('contact_person_relation', models.CharField(max_length=32)),
                ('contact_person_mobile', models.CharField(max_length=16)),
                ('contact_person_email', models.EmailField(max_length=64)),
                ('gpa', models.FloatField(validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mugshot', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='A personal image displayed in your profile.', upload_to=userena.models.upload_to_mugshot, verbose_name='mugshot')),
                ('privacy', models.CharField(choices=[(b'open', 'Open'), (b'registered', 'Registered'), (b'closed', 'Closed')], default=b'closed', help_text='Designates who can view your profile.', max_length=15, verbose_name='privacy')),
                ('role', models.CharField(choices=[('staff', 'Staff member'), ('intern', 'Intern')], max_length=8)),
                ('ar_first_name', models.CharField(max_length=32)),
                ('ar_middle_name', models.CharField(max_length=32)),
                ('ar_last_name', models.CharField(max_length=32)),
                ('en_first_name', models.CharField(max_length=32)),
                ('en_middle_name', models.CharField(max_length=32)),
                ('en_last_name', models.CharField(max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'permissions': (('view_profile', 'Can view profile'),),
            },
        ),
        migrations.AddField(
            model_name='intern',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intern', to='accounts.Profile'),
        ),
    ]
