# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_intern_alt_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='has_passport',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='passport_attachment',
            field=models.FileField(blank=True, null=True, upload_to='passport_attachments'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='passports'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='passport_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
