# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160804_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='privacy',
            field=models.CharField(choices=[(b'open', 'Open'), (b'registered', 'Registered'), (b'closed', 'Closed')], default=b'closed', help_text='Designates who can view your profile.', max_length=15, verbose_name='privacy'),
        ),
    ]
