# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160901_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='intern',
            name='passport',
            field=models.ImageField(default='', upload_to='passports'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intern',
            name='saudi_id',
            field=models.ImageField(default='', upload_to='saudi_ids'),
            preserve_default=False,
        ),
    ]
