# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-02 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161123_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abbreviation', models.CharField(max_length=10)),
                ('is_ksauhs', models.BooleanField(default=False)),
                ('is_agu', models.BooleanField(default=False)),
                ('start_month', month.models.MonthField(help_text='The month on which the batch is expected to start their medical internship')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('abbreviation', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('is_ksauhs', models.BooleanField(default=False)),
                ('is_agu', models.BooleanField(default=False)),
            ],
        ),
    ]
