# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-02 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170402_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ('-start_month',), 'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'Universities'},
        ),
        migrations.RenameField(
            model_name='intern',
            old_name='saudi_id',
            new_name='id_image',
        ),
        migrations.RenameField(
            model_name='intern',
            old_name='saudi_id_number',
            new_name='id_number',
        ),
        migrations.RenameField(
            model_name='intern',
            old_name='passport',
            new_name='passport_image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='ar_middle_name',
            new_name='ar_father_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='en_middle_name',
            new_name='en_father_name',
        ),
        migrations.AddField(
            model_name='intern',
            name='academic_transcript',
            field=models.FileField(blank=True, null=True, upload_to='academic_transcripts'),
        ),
        migrations.AddField(
            model_name='intern',
            name='graduation_date',
            field=month.models.MonthField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intern',
            name='medical_checklist',
            field=models.FileField(blank=True, null=True, upload_to='medical_checklists'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ar_grandfather_name',
            field=models.CharField(default='.', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='en_grandfather_name',
            field=models.CharField(default='.', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='internship_email',
            field=models.EmailField(default='email@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='internship_fax',
            field=models.CharField(default='+966112345678', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='internship_phone',
            field=models.CharField(default='+966112345678', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intern',
            name='alt_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='badge_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='has_passport',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='medical_record_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='student_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
