# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0023_auto_20161121_0146'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month', month.models.MonthField()),
                ('intern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Intern')),
            ],
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
        )
    ]
