# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 20:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('months', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freeze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', month.models.MonthField()),
            ],
        ),
        migrations.CreateModel(
            name='FreezeCancelRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', month.models.MonthField()),
                ('submission_datetime', models.DateTimeField(auto_now_add=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_cancel_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreezeCancelRequestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField()),
                ('comments', models.TextField()),
                ('response_datetime', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='months.FreezeCancelRequest')),
            ],
        ),
        migrations.CreateModel(
            name='FreezeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', month.models.MonthField()),
                ('justification', models.TextField()),
                ('submission_datetime', models.DateTimeField(auto_now_add=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreezeRequestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField()),
                ('comments', models.TextField()),
                ('response_datetime', models.DateTimeField(auto_now_add=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='months.FreezeRequest')),
            ],
        ),
        migrations.AddField(
            model_name='freeze',
            name='freeze_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='months.FreezeRequest'),
        ),
        migrations.AddField(
            model_name='freeze',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freezes', to=settings.AUTH_USER_MODEL),
        ),
    ]
