# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-02 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('months', '0002_auto_20161123_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezecancelrequestresponse',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='freezerequestresponse',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
