# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-11 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavesetting',
            name='max_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
