# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='codename',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='max_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
