# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-11 10:24
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Q


def forwards_func(apps, schema_editor):
    """
    Create default leave settings for KSAU-HS & AGU interns.
    """
    User = apps.get_model("auth", "User")
    LeaveType = apps.get_model("leaves", "LeaveType")
    LeaveSetting = apps.get_model("leaves", "LeaveSetting")

    leave_settings = list()

    for leave_type in LeaveType.objects.all():
        for user in User.objects.filter(profile__role='intern').filter(
            Q(profile__intern__university__is_ksauhs=True) | Q(profile__intern__university__is_agu=True)
        ):
            leave_settings.append(LeaveSetting(
                intern=user,
                type=leave_type,
                max_days=leave_type.max_days,
            ))

    LeaveSetting.objects.bulk_create(leave_settings)


def reverse_func(apps, schema_editor):
    """
    Remove all leave settings
    """
    LeaveSetting = apps.get_model("leaves", "LeaveSetting")
    LeaveSetting.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_auto_20170611_1340'),
    ]

    operations = [
        migrations.RunPython(
            forwards_func,
            reverse_func,
        )
    ]
