# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 08:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0002_auto_20161117_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavecancelrequest',
            old_name='original_request',
            new_name='leave_request',
        ),
        migrations.AddField(
            model_name='leavecancelrequest',
            name='intern',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='leave_cancel_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavecancelrequest',
            name='month',
            field=month.models.MonthField(default=0),
            preserve_default=False,
        ),
    ]
