# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-15 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_create_leave_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='rotation_request',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='leave_request_attachments'),
        ),
    ]
