# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-17 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_auto_20161117_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='rotation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='planner.RotationRequest'),
        ),
    ]
