# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_auto_20161117_2048'),
        ('rotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavecancelrequest',
            name='rotation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_cancel_requests', to='rotations.RotationRequest'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='rotation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='rotations.RotationRequest'),
        ),
    ]
