# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-10 20:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('codename', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-z_]+[a-z0-9_]*$', "Please use lowercase letters, numbers, and underscores only. You can't start with a number.")])),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Microsoft Word')], max_length=4)),
                ('template_file', models.FileField(upload_to='document_templates')),
            ],
        ),
    ]
