"""
Django settings for easy_internship project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import secrets

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secrets.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = secrets.DEBUG

ALLOWED_HOSTS = secrets.ALLOWED_HOSTS

ADMINS = secrets.ADMINS

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    'sitetree',
    'djng',
    'bootstrap3',
    'django_nyt',
    'rules.apps.AutodiscoverRulesConfig',
    'hospitals.apps.HospitalsConfig',
    'months.apps.MonthsConfig',
    'rotations.apps.RotationsConfig',
    'leaves.apps.LeavesConfig',
    'accounts.apps.AccountsConfig',
    'misc.apps.MiscConfig',
    'userena',  # Userena should be kept at the end in order to overwrite the 'base.html' template it has
    'guardian',
    'easy_thumbnails',
    'post_office',
    'protractor',
    'ckeditor',
    'ckeditor_uploader',
    'debug_toolbar',
)

MIDDLEWARE_CLASSES = (
    'djng.middleware.AngularUrlMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'easy_internship.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'easy_internship/templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'easy_internship.context_processors.settings_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'easy_internship.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = secrets.DATABASES


# Authentication

AUTHENTICATION_BACKENDS = (
    'rules.permissions.ObjectPermissionBackend',
    'userena.backends.UserenaAuthenticationBackend',
    'guardian.backends.ObjectPermissionBackend',
    'django.contrib.auth.backends.ModelBackend',
)

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Riyadh'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'frontend'),
    os.path.join(BASE_DIR, 'easy_internship/static'),
]
STATIC_URL = '/static/'
STATIC_ROOT = secrets.STATIC_ROOT

# Media files (user-uploaded files)

MEDIA_URL = '/media/'
MEDIA_ROOT = secrets.MEDIA_ROOT

# Fixtures

FIXTURE_DIRS = [
    os.path.join(BASE_DIR, 'easy_internship/fixtures'),
]

# Messages
#
# from django.contrib.messages import constants as message_constants
# MESSAGE_TAGS = {message_constants.ERROR: 'danger'}

# Email

EMAIL_BACKEND = 'post_office.EmailBackend'

POST_OFFICE = {
    'BACKENDS': {
        'default': secrets.POST_OFFICE_BACKEND,
    }
}

EMAIL_USE_TLS = secrets.EMAIL_USE_TLS
EMAIL_HOST = secrets.EMAIL_HOST
EMAIL_PORT = secrets.EMAIL_PORT
EMAIL_HOST_USER = secrets.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = secrets.EMAIL_HOST_PASSWORD

DEFAULT_FROM_EMAIL = secrets.DEFAULT_FROM_EMAIL
SERVER_EMAIL = secrets.SERVER_EMAIL

# Sites

SITE_ID = secrets.SITE_ID

# Logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'my_logs', 'debug.log'),  # FIXME: should create file if it doesn't exist
            'formatter': 'verbose'
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'simple'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

# Userena & Guardian

ANONYMOUS_USER_ID = -1
AUTH_PROFILE_MODULE = "accounts.Profile"

LOGIN_URL = '/accounts/signin/'
LOGOUT_URL = '/accounts/signout/'

USERENA_SIGNIN_REDIRECT_URL = '/'
USERENA_REDIRECT_ON_SIGNOUT = '/'

USERENA_WITHOUT_USERNAMES = True
USERENA_ACTIVATION_REQUIRED = True
USERENA_DEFAULT_PRIVACY = "closed"
USERENA_DISABLE_PROFILE_LIST = True
USERENA_HTML_EMAIL = True
USERENA_REGISTER_PROFILE = False
USERENA_REGISTER_USER = False
USERENA_PROFILE_DETAIL_TEMPLATE = "userena/profile_detail_custom.html"

# Django NYT

NYT_ENABLE_ADMIN = True
NYT_EMAIL_SENDER = secrets.NYT_EMAIL_SENDER

# Django debug toolbar

INTERNAL_IPS = ['127.0.0.1', 'localhost']

# Misc

SUPPORT_EMAIL_ADDRESS = secrets.SUPPORT_EMAIL_ADDRESS
CKEDITOR_UPLOAD_PATH = secrets.CKEDITOR_UPLOAD_PATH
CKEDITOR_IMAGE_BACKEND = "pillow"
