# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_auto_20161121_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='has_requirement',
            field=models.BooleanField(default=False, verbose_name='Has special requirements?'),
        ),
        migrations.AddField(
            model_name='department',
            name='requirement_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='requirement_file',
            field=models.FileField(blank=True, null=True, upload_to='hospital_requirements'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='has_requirement',
            field=models.BooleanField(default=False, verbose_name='Has special requirements?'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='requirement_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='requirement_file',
            field=models.FileField(blank=True, null=True, upload_to='hospital_requirements'),
        ),
    ]
