# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-10 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_auto_20161123_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='memo_handed_by_intern',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='requires_memo',
            field=models.BooleanField(default=True),
        ),
    ]
