# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-10 18:50
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    Department = apps.get_model("hospitals", "Department")
    for department in Department.objects.filter(hospital__is_kamc=True):
        department.requires_memo = False
        department.save()


def reverse_func(apps, schema_editor):
    Department = apps.get_model("hospitals", "Department")
    for department in Department.objects.filter(hospital__is_kamc=True):
        department.requires_memo = True
        department.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_auto_20161210_2023'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
