# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-30 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_auto_20161210_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDepartmentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=128)),
                ('contact_position', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('extension', models.CharField(max_length=16)),
                ('requires_memo', models.BooleanField(default=True)),
                ('memo_handed_by_intern', models.BooleanField(default=True)),
                ('has_requirement', models.BooleanField(default=False, verbose_name='Has special requirements?')),
                ('requirement_description', models.TextField(blank=True, null=True)),
                ('requirement_file', models.FileField(blank=True, null=True, upload_to='hospital_requirements')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='departmentmonthsettings',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospitals.Hospital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departmentmonthsettings',
            name='specialty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospitals.Specialty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departmentsettings',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospitals.Hospital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departmentsettings',
            name='specialty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospitals.Specialty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='memo_handed_by_intern',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='requires_memo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='location',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='hospitals.Hospital'),
        ),
        migrations.AddField(
            model_name='location',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='hospitals.Specialty'),
        ),
        migrations.AddField(
            model_name='customdepartmentdetail',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_department_details', to='hospitals.Hospital'),
        ),
        migrations.AddField(
            model_name='customdepartmentdetail',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_department_details', to='hospitals.Location'),
        ),
        migrations.AddField(
            model_name='customdepartmentdetail',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_department_details', to='hospitals.Specialty'),
        ),
        migrations.AddField(
            model_name='departmentmonthsettings',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.Location'),
        ),
        migrations.AddField(
            model_name='departmentsettings',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.Location'),
        ),
    ]
