# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-17 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_auto_20161210_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='contact_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='contact_position',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='email',
            field=models.EmailField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='extension',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='phone',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
