# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-30 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_auto_20170130_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='abbreviation',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
