# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-30 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0009_auto_20170130_0706'),
        ('rotations', '0007_auto_20170130_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='department',
            name='parent_department',
        ),
        migrations.RemoveField(
            model_name='department',
            name='specialty',
        ),
        migrations.AlterUniqueTogether(
            name='customdepartmentdetail',
            unique_together=set([('hospital', 'specialty', 'location')]),
        ),
        migrations.AlterUniqueTogether(
            name='departmentmonthsettings',
            unique_together=set([('month', 'hospital', 'specialty', 'location')]),
        ),
        migrations.RemoveField(
            model_name='departmentsettings',
            name='department',
        ),
        migrations.AlterUniqueTogether(
            name='departmentsettings',
            unique_together=set([('hospital', 'specialty', 'location')]),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.RemoveField(
            model_name='departmentmonthsettings',
            name='department',
        ),
    ]
