# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('contact_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('extension', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('abbreviation', models.CharField(max_length=16)),
                ('is_kamc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_month', month.models.MonthField()),
                ('intern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Intern')),
            ],
        ),
        migrations.CreateModel(
            name='PlanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submission_datetime', models.DateTimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('closure_datetime', models.DateTimeField()),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_requests', to='planner.Internship')),
            ],
        ),
        migrations.CreateModel(
            name='RequestedDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_in_database', models.BooleanField()),
                ('department_name', models.CharField(max_length=128)),
                ('department_contact_name', models.CharField(max_length=128)),
                ('department_email', models.EmailField(max_length=128)),
                ('department_phone', models.CharField(max_length=128)),
                ('department_extension', models.CharField(max_length=16)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_requests', to='planner.Department')),
                ('department_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.Hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', month.models.MonthField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='planner.Department')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='planner.Internship')),
            ],
        ),
        migrations.CreateModel(
            name='RotationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', month.models.MonthField()),
                ('plan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_requests', to='planner.PlanRequest')),
                ('requested_department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planner.RequestedDepartment')),
            ],
        ),
        migrations.CreateModel(
            name='RotationRequestForward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forward_datetime', models.DateTimeField(auto_now_add=True)),
                ('rotation_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forward', to='planner.RotationRequest')),
            ],
        ),
        migrations.CreateModel(
            name='RotationRequestForwardResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField()),
                ('response_memo', models.FileField(upload_to='forward_response_memos')),
                ('comments', models.TextField()),
                ('respondent_name', models.CharField(max_length=128)),
                ('response_datetime', models.DateTimeField(auto_now_add=True)),
                ('forward', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='planner.RotationRequestForward')),
            ],
        ),
        migrations.CreateModel(
            name='RotationRequestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField()),
                ('comments', models.TextField()),
                ('response_datetime', models.DateTimeField(auto_now_add=True)),
                ('rotation_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='planner.RotationRequest')),
            ],
        ),
        migrations.CreateModel(
            name='SeatAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', month.models.MonthField()),
                ('available_seat_count', models.PositiveIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='planner.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('abbreviation', models.CharField(max_length=4)),
                ('required_months', models.PositiveIntegerField()),
                ('parent_specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subspecialties', to='planner.Specialty')),
            ],
        ),
        migrations.AddField(
            model_name='seatavailability',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='planner.Specialty'),
        ),
        migrations.AddField(
            model_name='rotationrequest',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_requests', to='planner.Specialty'),
        ),
        migrations.AddField(
            model_name='rotation',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='planner.Specialty'),
        ),
        migrations.AddField(
            model_name='requesteddepartment',
            name='department_specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.Specialty'),
        ),
        migrations.AddField(
            model_name='department',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='planner.Hospital'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='planner.Department'),
        ),
        migrations.AddField(
            model_name='department',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='planner.Specialty'),
        ),
    ]
