# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planrequest',
            name='closure_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planrequest',
            name='submission_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
