# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20160621_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotationrequest',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
