# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20160715_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotationrequestforward',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rotationrequestforward',
            name='key',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
