# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 05:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20160715_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotationrequest',
            name='submission_datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 1, 5, 17, 14, 868073, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
