# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 05:19
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone


def transfer_submission_datetime(apps, schema_editor):
    PlanRequest = apps.get_model("planner", "PlanRequest")

    for pr in PlanRequest.objects.all():
        for rr in pr.rotation_requests.all():
            if pr.submission_datetime:
                rr.submission_datetime = pr.submission_datetime
            else:
                rr.submission_datetime = timezone.now()
            rr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_rotationrequest_submission_datetime'),
    ]

    operations = [
        migrations.RunPython(transfer_submission_datetime),
    ]
