# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 05:54
from __future__ import unicode_literals

from django.db import migrations


def transfer_rotation_requests_to_internship(apps, schema_editor):
    RotationRequest = apps.get_model("planner", "RotationRequest")

    for rr in RotationRequest.objects.all():
        rr.internship = rr.plan_request.internship
        rr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_auto_20160901_0554'),
    ]

    operations = [
        migrations.RunPython(transfer_rotation_requests_to_internship),
    ]
