# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_auto_20160901_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planrequest',
            name='internship',
        ),
        migrations.RemoveField(
            model_name='rotationrequest',
            name='plan_request',
        ),
        migrations.DeleteModel(
            name='PlanRequest',
        ),
    ]
