# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 08:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_auto_20160901_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotation',
            name='rotation_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.RotationRequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requesteddepartment',
            name='department_contact_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='requesteddepartment',
            name='department_email',
            field=models.EmailField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='requesteddepartment',
            name='department_extension',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\d{3}\\d*$', code='invalid_extension', message='Extension should be at least 3 digits long.')]),
        ),
        migrations.AlterField(
            model_name='requesteddepartment',
            name='department_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='requesteddepartment',
            name='department_phone',
            field=models.CharField(blank=True, max_length=128, validators=[django.core.validators.RegexValidator('^\\+\\d{12}$', code='invalid_phone_number', message='Phone number should follow the format +966XXXXXXXXX.')]),
        ),
    ]
