# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_auto_20160908_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotation',
            name='rotation_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planner.RotationRequest'),
        ),
    ]
