# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-16 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_auto_20160908_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotation',
            name='is_elective',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rotationrequest',
            name='is_elective',
            field=models.BooleanField(default=False),
        ),
    ]
