# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-07 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_auto_20160916_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatavailability',
            name='specialty',
        ),
    ]
