# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-07 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_remove_seatavailability_specialty'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seatavailability',
            unique_together=set([('month', 'department')]),
        ),
    ]
