# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_auto_20161007_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_criterion', models.CharField(choices=[('FCFS', 'First-come, First-serve'), ('GPA', 'GPA')], default='FCFS', max_length=4)),
                ('acceptance_start_date_interval', models.PositiveIntegerField(default=30)),
                ('acceptance_end_date_interval', models.PositiveIntegerField(default=30)),
            ],
        ),
    ]
