# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-20 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import month.models
import planner.models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_globalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentMonthSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', month.models.MonthField()),
                ('total_seats', models.PositiveIntegerField()),
                ('acceptance_criterion', models.CharField(choices=[('FCFS', 'First-come, First-serve'), ('GPA', 'GPA')], default='FCFS', max_length=4)),
                ('acceptance_start_date', models.DateTimeField(blank=True, null=True)),
                ('acceptance_end_date', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_settings', to='planner.Department')),
            ],
            bases=(planner.models.MonthSettingsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DepartmentSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance_criterion', models.CharField(choices=[('FCFS', 'First-come, First-serve'), ('GPA', 'GPA')], default='FCFS', max_length=4)),
                ('acceptance_start_date_interval', models.PositiveIntegerField(blank=True, null=True)),
                ('acceptance_end_date_interval', models.PositiveIntegerField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_settings', to='planner.Department')),
            ],
            bases=(planner.models.NonMonthSettingsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MonthSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', month.models.MonthField(unique=True)),
                ('acceptance_criterion', models.CharField(choices=[('FCFS', 'First-come, First-serve'), ('GPA', 'GPA')], default='FCFS', max_length=4)),
                ('acceptance_start_date', models.DateTimeField(blank=True, null=True)),
                ('acceptance_end_date', models.DateTimeField(blank=True, null=True)),
            ],
            bases=(planner.models.MonthSettingsMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='seatavailability',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='seatavailability',
            name='department',
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='acceptance_end_date_interval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='acceptance_start_date_interval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SeatAvailability',
        ),
        migrations.AlterUniqueTogether(
            name='departmentmonthsettings',
            unique_together=set([('month', 'department')]),
        ),
    ]
