# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-22 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_auto_20161020_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmonthsettings',
            name='acceptance_criterion',
            field=models.CharField(blank=True, choices=[('FCFS', 'First-come, First-serve'), ('GPA', 'GPA')], max_length=4, null=True),
        ),
    ]
