# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0019_auto_20161117_0030'),
    ]

    database_operations = [
        migrations.AlterModelTable('Hospital', 'hospitals_hospital'),
        migrations.AlterModelTable('Specialty', 'hospitals_specialty'),
        migrations.AlterModelTable('Department', 'hospitals_department'),
        migrations.AlterModelTable('GlobalSettings', 'hospitals_globalsettings'),
        migrations.AlterModelTable('MonthSettings', 'hospitals_monthsettings'),
        migrations.AlterModelTable('DepartmentSettings', 'hospitals_departmentsettings'),
        migrations.AlterModelTable('DepartmentMonthSettings', 'hospitals_departmentmonthsettings'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
        )
    ]
