# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0020_auto_20161121_0119'),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesteddepartment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_requests', to='hospitals.Department'),
        ),
        migrations.AlterField(
            model_name='requesteddepartment',
            name='department_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.Hospital'),
        ),
        migrations.AlterField(
            model_name='requesteddepartment',
            name='department_specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.Specialty'),
        ),
        migrations.AlterField(
            model_name='rotation',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='hospitals.Department'),
        ),
        migrations.AlterField(
            model_name='rotation',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='hospitals.Specialty'),
        ),
        migrations.AlterField(
            model_name='rotationrequest',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_requests', to='hospitals.Specialty'),
        ),
    ]
