# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0021_auto_20161121_0118'),
    ]

    state_operations = [
        migrations.DeleteModel('Hospital'),
        migrations.DeleteModel('Specialty'),
        migrations.DeleteModel('Department'),
        migrations.DeleteModel('GlobalSettings'),
        migrations.DeleteModel('MonthSettings'),
        migrations.DeleteModel('DepartmentSettings'),
        migrations.DeleteModel('DepartmentMonthSettings'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
        )
    ]
