# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0022_auto_20161121_0130'),
    ]

    database_operations = [
        migrations.AlterModelTable('Internship', 'months_internship'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations
        )
    ]
