# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0023_auto_20161121_0146'),
        ('months', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotation',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='months.Internship'),
        ),
        migrations.AlterField(
            model_name='rotationrequest',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_requests', to='months.Internship'),
        ),
    ]
