# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0024_auto_20161121_0145'),
    ]

    state_operations = [
        migrations.DeleteModel('Internship'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
        )
    ]
