# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0025_auto_20161121_0711'),
    ]

    database_operations = [
        migrations.AlterModelTable('Rotation', 'rotations_rotation'),
        migrations.AlterModelTable('RequestedDepartment', 'rotations_requesteddepartment'),
        migrations.AlterModelTable('RotationRequest', 'rotations_rotationrequest'),
        migrations.AlterModelTable('RotationRequestResponse', 'rotations_rotationrequestresponse'),
        migrations.AlterModelTable('RotationRequestForward', 'rotations_rotationrequestforward'),
        migrations.AlterModelTable('RotationRequestForwardResponse', 'rotations_rotationrequestforwardresponse'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
        )
    ]
