# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0026_auto_20161121_0721'),
        ('rotations', '0001_initial'),
        ('leaves', '0005_auto_20161121_0719'),
    ]

    operations = [
        # All RemoveField and DeleteModel operations were removed...
    ]
