# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0027_auto_20161121_0719'),
    ]

    state_operations = [
        migrations.DeleteModel('Rotation'),
        migrations.DeleteModel('RequestedDepartment'),
        migrations.DeleteModel('RotationRequest'),
        migrations.DeleteModel('RotationRequestResponse'),
        migrations.DeleteModel('RotationRequestForward'),
        migrations.DeleteModel('RotationRequestForwardResponse'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
        )
    ]
